<a href="https://colab.research.google.com/github/kpodwysocka/Lake/blob/main/notebooks/data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# RAW data
data = {
    "order_id": [1, 2, 3, 4],
    "customer_id": [101, 102, 101, 103],
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "amount": ["1200", "25", "75", "300"],
    "date": ["2024-01-05", "2024-01-06", "2024-01-07", "2024-01-08"]
}

df_raw = pd.DataFrame(data)

print("RAW DATA:")
display(df_raw)

RAW DATA:

   order_id  customer_id   product amount        date
0         1          101    Laptop   1200  2024-01-05
1         2          102     Mouse     25  2024-01-06
2         3          101  Keyboard     75  2024-01-07
3         4          103   Monitor    300  2024-01-08

In [2]:
# PROCESSED layer
df_processed = df_raw.copy()

df_processed["amount"] = df_processed["amount"].astype(float)
df_processed["date"] = pd.to_datetime(df_processed["date"])

print("PROCESSED DATA:")
display(df_processed)

PROCESSED DATA:

   order_id  customer_id   product  amount       date
0         1          101    Laptop  1200.0 2024-01-05
1         2          102     Mouse    25.0 2024-01-06
2         3          101  Keyboard    75.0 2024-01-07
3         4          103   Monitor   300.0 2024-01-08

In [3]:
# CURATED layer (aggregated for analysis)
df_curated = df_processed.groupby("customer_id")["amount"].sum().reset_index()

print("CURATED DATA:")
display(df_curated)

CURATED DATA:

   customer_id  amount
0          101  1275.0
1          102    25.0
2          103   300.0